# Generated by Django 4.1.5 on 2023-02-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='data_birth',
            field=models.DateField(blank=True, default='2000-11-11', verbose_name='дата рождения'),
        ),
        migrations.AddField(
            model_name='artist',
            name='role',
            field=models.CharField(blank=True, max_length=255, verbose_name='роль'),
        ),
    ]
