# Generated by Django 4.1.5 on 2023-02-17 13:37

from django.db import migrations


def add_artist_rows(apps, schema_editor):
    model = apps.get_model('books.Artist')

    rows = [
        ('Курт', 'Кобеин'),
        ('Пол', 'Маккартни')
    ]

    for f, l in rows:
        model.objects.create(first_name=f, last_name=l)


def back_migrate_in_0002(apps, schema_editor):
    model = apps.get_model('books.Artist')

    model.objects.filter(first_name__in=('Курт', 'Пол')).delete()


class Migration(migrations.Migration):
    dependencies = [
        ('books', '0002_artist_data_birth_artist_role'),
    ]

    operations = [
        migrations.RunPython(add_artist_rows, back_migrate_in_0002)
    ]
